# Generated by Django 5.0.4 on 2024-05-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('starting_bid', models.IntegerField()),
                ('image', models.CharField(max_length=150, verbose_name='image url')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
