# Generated by Django 5.0.4 on 2024-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_starting_bid_listing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
